In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Atividade de vendas no Brasil

## Entregável 1 NumPy

### A. Criando arrays

In [ ]:
#Lendo o arquivo csv com pandas
df = pd.read_csv("vendas_brasil_1.csv")

#Criando arrays para as colunas numéricas do dataset usando numpy
preco_unitario_np = df['preco_unitario'].to_numpy()

custo_unitario_np = df['custo_unitario'].to_numpy()

quantidade_np = df['quantidade'].to_numpy()

desconto_pct_np = df['desconto_pct'].to_numpy()

receita_total_np = df['receita_total'].to_numpy()

frete_np = df['frete'].to_numpy()
print("Dataset")
print(df)
print(f'Os arrays criados a partir deste dataset foram:\nPreço unitario:{preco_unitario_np}\ncusto unitario:{custo_unitario_np}\ndesconto pct:{desconto_pct_np}\nquantidade:{quantidade_np}\nreceita total:{receita_total_np}\nfrete:{frete_np} ')

Dataset
       data_venda  mes          cidade  canal_venda    categoria  \
0      2022-04-13    4  Rio de Janeiro   App Mobile  Eletrônicos
1      2023-03-12    3          Manaus     Site Web    Vestuário
2      2022-09-28    9         Goiânia   App Mobile    Vestuário
3      2022-04-17    4       Fortaleza     Site Web    Vestuário
4      2022-03-13    3  Belo Horizonte   App Mobile     Esportes
...           ...  ...             ...          ...          ...
37612  2023-12-31    3    Porto Alegre   App Mobile  Alimentação
37613  2023-12-31    9        Salvador     Site Web  Alimentação
37614  2023-12-31    2        Salvador  Loja Física  Alimentação
37615  2023-12-31   11       São Paulo     Site Web     Esportes
37616  2023-12-31    4       Fortaleza   Televendas  Eletrônicos

               produto       vendedor fidelidade_cliente  preco_unitario  \
0             Notebook    Bruno Souza           Diamante          739.39
1             Camiseta    Elisa Costa             Bronze          187.48
2                Tênis    João Vieira             Bronze           76.11
3          Calça Jeans   Carla Mendes             Bronze          145.86
4            Bicicleta    João Vieira             Bronze          133.92
...                ...            ...                ...             ...
37612  Barra de Cereal     Gabi Alves             Bronze           73.11
37613     Mel Orgânico  Henrique Dias             Bronze           76.62
37614     Whey Protein    Fábio Ramos             Bronze           55.15
37615   Tapete de Yoga    João Vieira             Bronze          197.09
37616           Tablet     Inês Nunes              Prata         1057.41

       custo_unitario  ...  quantidade  desconto_pct  receita_total  frete  \
0              561.75  ...          10           5.2        6933.48   8.68
1              135.15  ...           5           0.6         930.28    NaN
2               61.40  ...          14           0.7        1058.50   7.98
3               88.53  ...          11           0.6        1592.43  20.49
4              107.25  ...           1          19.5         107.64  22.89
...               ...  ...         ...           ...            ...    ...
37612           47.38  ...           9          20.3         524.49   8.15
37613           55.50  ...          12          10.7         820.52  41.74
37614           36.94  ...           7           0.0         384.44  85.35
37615          167.23  ...           7          10.9        1960.18  30.99
37616          870.69  ...           4          10.0        3795.73  27.23

       avaliacao_cliente  prazo_entrega_dias  devolucao  entrega_no_prazo  \
0                   4.92                 5.0      False              True
1                   4.98                19.0       True             False
2                   3.47                 NaN       True              True
3                   4.50                16.0      False              True
4                   3.49                13.0      False              True
...                  ...                 ...        ...               ...
37612               4.95                 NaN      False             False
37613               4.49                19.0      False             False
37614               4.02                14.0      False              True
37615               3.50                 6.0      False              True
37616               4.02                16.0      False              True

       alta_temporada  flag_outlier_preco
0               False               False
1               False               False
2               False               False
3               False               False
4               False               False
...               ...                 ...
37612           False               False
37613           False               False
37614           False               False
37615            True               False
37616           False                True

[37617 rows x 21 columns]
Os arrays criados a partir deste dataset foram:
Preço unitario:[ 739.39  187.48   76.11 ...   55.15  197.09 1057.41]
custo unitario:[561.75 135.15  61.4  ...  36.94 167.23 870.69]
desconto pct:[ 5.2  0.6  0.7 ...  0.  10.9 10. ]
quantidade:[10  5 14 ...  7  7  4]
receita total:[6933.48  930.28 1058.5  ...  384.44 1960.18 3795.73]
frete:[ 8.68   nan  7.98 ... 85.35 30.99 27.23]

### B. Cálculos com operações vetorizadas

In [ ]:
#calculando valores importantes sobre o dataset
valor_bruto = preco_unitario_np * quantidade_np
valor_desconto = valor_bruto * (desconto_pct_np/100)
custo_total = custo_unitario_np * quantidade_np
lucro_estimado = receita_total_np - custo_total

print(f'valor bruto dos produtos: {valor_bruto}')
print(f'desconto dos produtos: {valor_desconto}')
print(f'custo total da produção dos produtos: {custo_total}')
print(f'lucro estimado da venda de cada produto: {lucro_estimado}')

valor bruto dos produtos: [7393.9   937.4  1065.54 ...  386.05 1379.63 4229.64]
desconto dos produtos: [384.4828    5.6244    7.45878 ...   0.      150.37967 422.964  ]
custo total da produção dos produtos: [5617.5   675.75  859.6  ...  258.58 1170.61 3482.76]
lucro estimado da venda de cada produto: [1315.98  254.53  198.9  ...  125.86  789.57  312.97]

### C. Máscaras booleanas

In [ ]:
#Filtrando situações inusitadas do dataset

media_receita = np.mean(receita_total_np)
vendas_acima_media = receita_total_np[receita_total_np > media_receita]

vendas_prejuizo = lucro_estimado[lucro_estimado < 0]

media_desconto = np.mean(desconto_pct_np)
vendas_desconto_alta = desconto_pct_np[desconto_pct_np > media_desconto]

print(f'quantidade de vendas com receita acima da média: {len(vendas_acima_media)}')
print(f'quantidade vendas que geraram prejuízo: {len(vendas_prejuizo)}')
print(f'quantidade de vendas com desconto acima da média: {len(vendas_desconto_alta)}')
print(f'\nquantidade de vendas totais: {len(df['data_venda'])}')

quantidade de vendas com receita acima da média: 9236
quantidade vendas que geraram prejuízo: 2168
quantidade de vendas com desconto acima da média: 17853

quantidade de vendas totais: 37617

### D. Agregações

In [ ]:
#calculando medidas gerais para ánalise

media_das_receitas = np.mean(receita_total_np)

maior_receita = np.max(receita_total_np)

menor_receita = np.min(receita_total_np)

media_dos_lucros = np.mean(lucro_estimado)

quantidade_vendas_prejuizo = len(vendas_prejuizo)

print(f'media das receitas: {media_das_receitas}')
print(f'maior receita: {maior_receita}')
print(f'menor receita: {menor_receita}')
print(f'media dos lucros: {media_dos_lucros}')
print(f'quantidade de vendas com prejuizo: {quantidade_vendas_prejuizo}')

media das receitas: 1891.6881729005502
maior receita: 58430.28
menor receita: 3.7
media dos lucros: 513.187152883005
quantidade de vendas com prejuizo: 2168

### Conclusões gerais

Observando o dataset apenas com funções matematicas e de array do numpy podemos observar algumas inconsistências.

Dentro das vendas que análisamos vemos que temos alguns outliers tendo em vista que a média das receitas é 1891 enquanto a maior e menor receita que vimos são respectivamente 58430 e 3.

Podemos notar tambem que existem 2168 produtos onde o lucro obtido é negativo, gerando necessidade de uma maior atenção e ánalise em tais objetos

## Entregável 2 Pandas

### A. Primeiro olhar no dataset

In [ ]:
#explorando de forma geral o dataset usando pandas

print("Exibindo as 5 primeiras linhas do dataset:\n")
df.head()

Exibindo as 5 primeiras linhas do dataset:

,data_venda,mes,cidade,canal_venda,categoria,produto,vendedor,fidelidade_cliente,preco_unitario,custo_unitario,...,quantidade,desconto_pct,receita_total,frete,avaliacao_cliente,prazo_entrega_dias,devolucao,entrega_no_prazo,alta_temporada,flag_outlier_preco
0,2022-04-13,4,Rio de Janeiro,App Mobile,Eletrônicos,Notebook,Bruno Souza,Diamante,739.39,561.75,...,10,5.2,6933.48,8.68,4.92,5.0,False,True,False,False
1,2023-03-12,3,Manaus,Site Web,Vestuário,Camiseta,Elisa Costa,Bronze,187.48,135.15,...,5,0.6,930.28,NaN,4.98,19.0,True,False,False,False
2,2022-09-28,9,Goiânia,App Mobile,Vestuário,Tênis,João Vieira,Bronze,76.11,61.40,...,14,0.7,1058.50,7.98,3.47,NaN,True,True,False,False
3,2022-04-17,4,Fortaleza,Site Web,Vestuário,Calça Jeans,Carla Mendes,Bronze,145.86,88.53,...,11,0.6,1592.43,20.49,4.50,16.0,False,True,False,False
4,2022-03-13,3,Belo Horizonte,App Mobile,Esportes,Bicicleta,João Vieira,Bronze,133.92,107.25,...,1,19.5,107.64,22.89,3.49,13.0,False,True,False,False

In [ ]:
print("Exibindo a estrutura do nosso dataset")
df.info()

Exibindo a estrutura do nosso dataset
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37617 entries, 0 to 37616
Data columns (total 21 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   data_venda          37617 non-null  object
 1   mes                 37617 non-null  int64
 2   cidade              37617 non-null  object
 3   canal_venda         37567 non-null  object
 4   categoria           37617 non-null  object
 5   produto             37617 non-null  object
 6   vendedor            37577 non-null  object
 7   fidelidade_cliente  37617 non-null  object
 8   preco_unitario      37617 non-null  float64
 9   custo_unitario      37617 non-null  float64
 10  margem_pct          37535 non-null  float64
 11  quantidade          37617 non-null  int64
 12  desconto_pct        37617 non-null  float64
 13  receita_total       37617 non-null  float64
 14  frete               35738 non-null  float64
 15  avaliacao_cliente   34662 non-null  float64
 16  prazo_entrega_dias  36113 non-null  float64
 17  devolucao           37617 non-null  bool
 18  entrega_no_prazo    37617 non-null  bool
 19  alta_temporada      37617 non-null  bool
 20  flag_outlier_preco  37617 non-null  bool
dtypes: bool(4), float64(8), int64(2), object(7)
memory usage: 5.0+ MB

In [ ]:
print("Exibindo um resumo das informações estatisticas do nosso dataset")
df.describe()

Exibindo um resumo das informações estatisticas do nosso dataset

,mes,preco_unitario,custo_unitario,margem_pct,quantidade,desconto_pct,receita_total,frete,avaliacao_cliente,prazo_entrega_dias
count,37617.000000,37617.000000,37617.000000,37535.000000,37617.000000,37617.000000,37617.000000,35738.000000,34662.000000,36113.000000
mean,6.517691,253.214933,183.620999,22.714776,7.481750,9.494048,1891.688173,29.885737,3.912094,10.017113
std,3.439296,316.742367,231.376757,8.670213,4.322273,9.097484,2972.445759,24.765161,0.932256,5.477487
min,1.000000,4.940000,3.010000,-0.570000,1.000000,0.000000,3.700000,3.750000,1.000000,1.000000
25%,4.000000,68.960000,49.550000,16.380000,4.000000,0.300000,364.280000,12.190000,3.490000,5.000000
50%,7.000000,111.300000,80.990000,22.700000,7.000000,9.000000,789.570000,22.250000,4.010000,10.000000
75%,9.000000,257.680000,186.570000,29.250000,11.000000,19.000000,1853.210000,39.480000,4.520000,15.000000
max,12.000000,9008.600000,6578.260000,44.270000,161.000000,26.000000,58430.280000,243.820000,5.000000,19.000000

In [ ]:
print("exibindo o número de linhas e colunas do nosso dataset")
df.shape

exibindo o número de linhas e colunas do nosso dataset

(37617, 21)

In [ ]:
print("exibindo o número de nulos do nosso dataset por cada coluna")
df.isna().sum()

exibindo o número de nulos do nosso dataset por cada coluna

data_venda               0
mes                      0
cidade                   0
canal_venda             50
categoria                0
produto                  0
vendedor                40
fidelidade_cliente       0
preco_unitario           0
custo_unitario           0
margem_pct              82
quantidade               0
desconto_pct             0
receita_total            0
frete                 1879
avaliacao_cliente     2955
prazo_entrega_dias    1504
devolucao                0
entrega_no_prazo         0
alta_temporada           0
flag_outlier_preco       0
dtype: int64

In [ ]:
print("exibi o total de dados nulos no dataset")
df.isna().sum().sum()

exibi o total de dados nulos no dataset

np.int64(6510)

1- Existem 37617 linhas e 21 colunas

2- Sim, existe um total de 6510 dados nulos espalhados pelas colunas do dataset

3- as colunas:

*   mes
*   preco_unitario
*   custo_unitario
*   margem_pct
*   quantidade
*   desconto_pct
*   receita_total
*   frete
*   avaliação_cliente
*   prazo_entrega_dia

4- as colunas:


*   data_venda
*   cidade
*   canal_venda
*   categoria
*   produto
*   vendedor
*   fidelidade_cliente
*   devolucao
*   entrega_no_prazo
*   alta_temporada
*   flag_outlier_preco

### B. Limpeza e tratamento

In [ ]:
#convertendo a coluna data para datatype
df['data_venda'] = pd.to_datetime(df['data_venda'], format='mixed')

#padronizando os nomes das cidades
df['cidade'] = df['cidade'].str.upper()
mapeamento_cidades = {
    'RIO': 'RIO DE JANEIRO',
    'RJ': 'RIO DE JANEIRO',
    'RIO DEJANEIRO': 'RIO DE JANEIRO',
    'CURTIBA': 'CURITIBA',
    'SP': 'SÃO PAULO',
    'S. PAULO': 'SÃO PAULO',
    'SAO PAULO': 'SÃO PAULO',
    'BH': 'BELO HORIZONTE',
    'B. HORIZONTE': 'BELO HORIZONTE',
    'SLAVADOR': 'SALVADOR'
    }
df['cidade'] = df['cidade'].str.strip()
df['cidade'] = df['cidade'].replace(mapeamento_cidades)
df['cidade'].value_counts()

#Analisando a coluna avaliacao_cliente para decidir a melhor forma de substituir dados faltantes
"""
print(f'Analisando a coluna "avaliacao_cliente"')
print(f'média: {df['avaliacao_cliente'].mean()}')
print(f'maior coluna: {df['avaliacao_cliente'].max()}')
print(f'menor coluna: {df['avaliacao_cliente'].min()}')
"""
media_avaliacao_clientes = df['avaliacao_cliente'].mean()
df['avaliacao_cliente'] = df['avaliacao_cliente'].fillna(media_avaliacao_clientes)
df.isna().sum()

#Analisando a coluna frete para decidir a melhor forma de substituir dados faltantes
'''
print(f'Analisando a coluna "frete"')
print(f'{df['frete']}')
'''
df['frete'] = df['frete'].fillna(0)
df.isna().sum()
df['data_venda']

0       2022-04-13
1       2023-03-12
2       2022-09-28
3       2022-04-17
4       2022-03-13
           ...
37612   2023-12-31
37613   2023-12-31
37614   2023-12-31
37615   2023-12-31
37616   2023-12-31
Name: data_venda, Length: 37617, dtype: datetime64[ns]

Decidi substituir os dados faltantes da coluna 'frete' por 0 pois acho plausível supor que os dados nulos que aparecem são devidos a não necessidade de entrega do produto fazendo o frete não existir.

Como a coluna 'avaliacao_clientes' não possuia outliers grandes a melhor opção para substituir os dados faltantes é muda-los pela média da própria coluna.

Dessa maneira evitamos um viés muito grande na ánalise do noss0 dataset

### C. Criação de novas colunas

In [ ]:
#Criando uma coluna para o ano das vendas
df['ano_venda'] = df['data_venda'].dt.year
df[['ano_venda','data_venda']]

#Criando uma coluna para o lucro total
df['lucro_total'] = lucro_estimado #Variavel "lucro_estimado" criada em 1.B Calculos com operações vetorizadas
df['lucro_total']

#Criando uma coluna para receita liquida
df['receita_liquida'] = df['receita_total'] - df['desconto_pct'] - df['frete']
df[['receita_liquida', 'receita_total']].head()

#Criando uma coluna para faixa de receita
df['faixa_receita'] = df['receita_total'].apply(lambda x: 'alta' if x > media_das_receitas else 'baixa')
df[['faixa_receita', 'receita_total']]

      faixa_receita  receita_total
0              alta        6933.48
1             baixa         930.28
2             baixa        1058.50
3             baixa        1592.43
4             baixa         107.64
...             ...            ...
37612         baixa         524.49
37613         baixa         820.52
37614         baixa         384.44
37615          alta        1960.18
37616          alta        3795.73

[37617 rows x 2 columns]

### D. Filtros

In [ ]:
#Criando um filtro para saber quais receitas foram altas
receita_alta = df[df['faixa_receita'] == 'alta']
receita_alta

#Filtro para saber quais vendas tiveram devolução
vendas_com_devolucao = df[df['devolucao'] == True]
df['devolucao'].value_counts() #Nenhum dado fora do comum
vendas_com_devolucao

#Filtrando quais vendas foram da categoria Alimentação
vendas_alimentacao = df[df['categoria'] == 'Alimentação']
vendas_alimentacao

print(f'Os filtros criados foram:\nReceitas altas:\n{receita_alta}\nitens devolvidos\n{vendas_com_devolucao}\nquais vendas foram para Alimentação:\n{vendas_alimentacao}')

Os filtros criados foram:
Receitas altas:
      data_venda  mes          cidade  canal_venda    categoria  \
0     2022-04-13    4  RIO DE JANEIRO   App Mobile  Eletrônicos
11    2022-11-27   11       SÃO PAULO     Site Web     Esportes
15    2022-04-10    4        SALVADOR  Marketplace  Eletrônicos
17    2022-05-11    5  BELO HORIZONTE   App Mobile  Eletrônicos
20    2022-12-10   12          RECIFE     Site Web  Eletrônicos
...          ...  ...             ...          ...          ...
37593 2023-12-31    2          MANAUS     Site Web  Eletrônicos
37603 2023-12-31    9  RIO DE JANEIRO   App Mobile  Eletrônicos
37605 2023-12-31    3       FORTALEZA  Marketplace     Esportes
37615 2023-12-31   11       SÃO PAULO     Site Web     Esportes
37616 2023-12-31    4       FORTALEZA   Televendas  Eletrônicos

              produto      vendedor fidelidade_cliente  preco_unitario  \
0            Notebook   Bruno Souza           Diamante          739.39
11            Raquete   João Vieira              Prata          130.74
15         Smartphone      Ana Lima             Bronze         1213.88
17         Smartwatch   Elisa Costa              Prata          732.37
20         Smartphone    Inês Nunes              Prata          603.40
...               ...           ...                ...             ...
37593          Tablet    Gabi Alves               Ouro          565.19
37603          Tablet    Inês Nunes              Prata          963.50
37605  Tapete de Yoga  Carla Mendes             Bronze          352.25
37615  Tapete de Yoga   João Vieira             Bronze          197.09
37616          Tablet    Inês Nunes              Prata         1057.41

       custo_unitario  ...  avaliacao_cliente  prazo_entrega_dias  devolucao  \
0              561.75  ...               4.92                 5.0      False
11             101.92  ...               4.52                14.0      False
15             843.05  ...               3.52                12.0      False
17             536.37  ...               2.94                 4.0      False
20             394.18  ...               4.47                13.0      False
...               ...  ...                ...                 ...        ...
37593          385.88  ...               4.02                17.0      False
37603          608.11  ...               3.49                 3.0      False
37605          256.20  ...               3.52                 7.0      False
37615          167.23  ...               3.50                 6.0      False
37616          870.69  ...               4.02                16.0      False

       entrega_no_prazo  alta_temporada  flag_outlier_preco  ano_venda  \
0                  True           False               False       2022
11                False            True               False       2022
15                False           False                True       2022
17                 True           False               False       2022
20                 True            True               False       2022
...                 ...             ...                 ...        ...
37593             False           False               False       2023
37603              True           False                True       2023
37605              True           False               False       2023
37615              True            True               False       2023
37616              True           False                True       2023

       lucro_total  receita_liquida  faixa_receita
0          1315.98          6919.60           alta
11          944.44          2159.98           alta
15         2044.61          7892.88           alta
17           96.37          3241.17           alta
20         5727.86         11171.63           alta
...            ...              ...            ...
37593       548.96          3539.67           alta
37603      1513.97          4530.93           alta
37605       807.62          3321.98           alta
37615       789.57          1918.29           alta
37616       312.97          3758.50           alta

[9236 rows x 25 columns]
itens devolvidos
      data_venda  mes          cidade  canal_venda    categoria  \
1     2023-03-12    3          MANAUS     Site Web    Vestuário
2     2022-09-28    9         GOIÂNIA   App Mobile    Vestuário
7     2023-09-07    9          MANAUS   App Mobile  Alimentação
18    2023-10-24   10          MANAUS     Site Web    Vestuário
21    2023-05-07    5       SÃO PAULO  Loja Física  Eletrônicos
...          ...  ...             ...          ...          ...
37522 2023-12-31   11        SALVADOR  Marketplace     Esportes
37525 2023-12-31   11        CURITIBA  Loja Física     Esportes
37533 2023-12-31    5  BELO HORIZONTE   App Mobile  Alimentação
37583 2023-12-31    2          MANAUS  Loja Física  Eletrônicos
37589 2023-12-31    4  RIO DE JANEIRO   App Mobile  Eletrônicos

              produto       vendedor fidelidade_cliente  preco_unitario  \
1            Camiseta    Elisa Costa             Bronze          187.48
2               Tênis    João Vieira             Bronze           76.11
7        Mel Orgânico     Inês Nunes              Prata           35.72
18           Camiseta   Carla Mendes              Prata           65.73
21         Smartwatch     Gabi Alves             Bronze          892.83
...               ...            ...                ...             ...
37522       Bicicleta   Carla Mendes             Bronze          195.87
37525     Luva de Box       Ana Lima              Prata          248.42
37533         Granola  Henrique Dias              Prata           48.60
37583      Smartwatch  Henrique Dias             Bronze          846.16
37589  Fone Bluetooth    Fábio Ramos             Bronze          899.09

       custo_unitario  ...  avaliacao_cliente  prazo_entrega_dias  devolucao  \
1              135.15  ...           4.980000                19.0       True
2               61.40  ...           3.470000                 NaN       True
7               21.62  ...           3.030000                18.0       True
18              41.26  ...           3.912094                16.0       True
21             660.58  ...           1.050000                18.0       True
...               ...  ...                ...                 ...        ...
37522          161.39  ...           2.950000                 7.0       True
37525          183.21  ...           2.040000                13.0       True
37533           36.51  ...           4.490000                14.0       True
37583          697.37  ...           1.000000                10.0       True
37589          734.88  ...           4.040000                 8.0       True

       entrega_no_prazo  alta_temporada  flag_outlier_preco  ano_venda  \
1                 False           False               False       2023
2                  True           False               False       2022
7                 False           False               False       2023
18                 True           False               False       2023
21                 True           False                True       2023
...                 ...             ...                 ...        ...
37522              True            True               False       2023
37525              True            True               False       2023
37533              True           False               False       2023
37583              True           False                True       2023
37589             False           False                True       2023

       lucro_total  receita_liquida  faixa_receita
1           254.53           929.68          baixa
2           198.90          1049.82          baixa
7            51.63           141.87          baixa
18           99.72           208.15          baixa
21         1562.81          6833.26           alta
...            ...              ...            ...
37522       969.54          3059.76           alta
37525      1157.31          3322.96           alta
37533        -2.97           140.73          baixa
37583       684.49          8330.93           alta
37589      -264.88          3365.04           alta

[3532 rows x 25 columns]
quais vendas foram para Alimentação:
      data_venda  mes          cidade  canal_venda    categoria  \
7     2023-09-07    9          MANAUS   App Mobile  Alimentação
8     2022-05-02    5       SÃO PAULO     Site Web  Alimentação
27    2023-04-05    4          MANAUS   App Mobile  Alimentação
30    2022-09-10    9  RIO DE JANEIRO  Marketplace  Alimentação
31    2023-07-15    7  BELO HORIZONTE   App Mobile  Alimentação
...          ...  ...             ...          ...          ...
37590 2023-12-31   11          RECIFE   Televendas  Alimentação
37594 2023-12-31    2          MANAUS     Site Web  Alimentação
37612 2023-12-31    3    PORTO ALEGRE   App Mobile  Alimentação
37613 2023-12-31    9        SALVADOR     Site Web  Alimentação
37614 2023-12-31    2        SALVADOR  Loja Física  Alimentação

               produto       vendedor fidelidade_cliente  preco_unitario  \
7         Mel Orgânico     Inês Nunes              Prata           35.72
8         Whey Protein    Bruno Souza              Prata           31.18
27        Whey Protein    Fábio Ramos             Bronze           28.04
30     Barra de Cereal    João Vieira              Prata           53.57
31     Barra de Cereal       Ana Lima              Prata           67.53
...                ...            ...                ...             ...
37590     Whey Protein   Carla Mendes             Bronze           61.86
37594           Azeite    Bruno Souza              Prata           68.47
37612  Barra de Cereal     Gabi Alves             Bronze           73.11
37613     Mel Orgânico  Henrique Dias             Bronze           76.62
37614     Whey Protein    Fábio Ramos             Bronze           55.15

       custo_unitario  ...  avaliacao_cliente  prazo_entrega_dias  devolucao  \
7               21.62  ...               3.03                18.0       True
8               26.55  ...               4.46                 6.0      False
27              17.66  ...               3.49                14.0      False
30              33.99  ...               3.55                 5.0      False
31              44.31  ...               4.47                 7.0      False
...               ...  ...                ...                 ...        ...
37590           45.88  ...               4.97                 7.0      False
37594           56.00  ...               1.01                 1.0      False
37612           47.38  ...               4.95                 NaN      False
37613           55.50  ...               4.49                19.0      False
37614           36.94  ...               4.02                14.0      False

       entrega_no_prazo  alta_temporada  flag_outlier_preco  ano_venda  \
7                 False           False               False       2023
8                  True           False               False       2022
27                 True           False               False       2023
30                 True           False               False       2022
31                 True           False               False       2023
...                 ...             ...                 ...        ...
37590              True            True               False       2023
37594              True           False               False       2023
37612             False           False               False       2023
37613             False           False               False       2023
37614              True           False               False       2023

       lucro_total  receita_liquida  faixa_receita
7            51.63           141.87          baixa
8           -14.01           187.32          baixa
27           37.16            88.78          baixa
30           67.75           147.13          baixa
31          137.70           539.46          baixa
...            ...              ...            ...
37590        71.00           135.53          baixa
37594        15.09           306.51          baixa
37612        98.07           496.04          baixa
37613       154.52           768.08          baixa
37614       125.86           299.09          baixa

[7472 rows x 25 columns]

Com os filtros pudemos encontrar quais foram as receitas que tiveram um alto valor(valor acima da média), temos uma noção de quais vendas tiveram devolução e quantas e quais vendas foram da categoria de Alimetnação

### E. Agrupamentos com groupby

In [ ]:
#Calculando a receita que cada categoria gerou
receita_categoria = df.groupby('categoria')['receita_total'].sum()
receita_categoria

#Descobrindo qual canal de venda vendeu em maior quantidade
canal_mais_vendas = df.groupby('canal_venda')['quantidade'].sum()
canal_mais_vendas

#Analisando qual cidade teve maior receita
cidade_maior_receita = df.groupby('cidade')['receita_total'].sum()
cidade_maior_receita

cidade
BELO HORIZONTE    6914747.61
CURITIBA          6993175.07
FORTALEZA         7242081.82
GOIÂNIA           7178113.69
MANAUS            7459161.23
PORTO ALEGRE      7048428.17
RECIFE            7662241.79
RIO DE JANEIRO    6880176.34
SALVADOR          6918656.01
SÃO PAULO         6862852.27
Name: receita_total, dtype: float64

### F. Merge

In [ ]:
#Criando uma tabela de regiões para ligar cada cidade do dataset a uma região
regioes = {
    'cidade': ['RIO DE JANEIRO', 'SÃO PAULO', 'BELO HORIZONTE', 'CURITIBA', 'FORTALEZA', 'GOIÂNIA', 'MANAUS', 'PORTO ALEGRE','RECIFE', 'SALVADOR'],
    'regioes': ['SUDESTE', 'SUDESTE', 'SUDESTE', 'SUL', 'NORDESTE', 'CENTRO-OESTE', 'NORTE', 'SUL', 'NORDESTE', 'NORDESTE']
}
df_regioes = pd.DataFrame(regioes)
df_regioes

df_atualizado = pd.merge(df, df_regioes, on='cidade', how='left')
receita_por_regiao = df_atualizado.groupby('regioes')['receita_total'].sum()
receita_por_regiao

regioes
CENTRO-OESTE     7178113.69
NORDESTE        21822979.62
NORTE            7459161.23
SUDESTE         20657776.22
SUL             14041603.24
Name: receita_total, dtype: float64

## Entregável 3 Seaborn